<script setup lang="ts">
import { apiErrorMessage } from '@/app/http'
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { searchTasks } from './task.api'
import { shanghaiDate } from './shanghai-time'
import TaskFilters from './TaskFilters.vue'
import TaskRow from './TaskRow.vue'
import { type TaskPage, type TaskSearch } from './task.types'
const props = withDefaults(defineProps<{ dashboard?: boolean; refreshToken?: number }>(), { dashboard: false, refreshToken: 0 })
const router = useRouter(); const loading = ref(false); const errorMessage = ref(''); const emptyPage = (): TaskPage => ({ content: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }); const page = ref<TaskPage>(emptyPage()); let requestSequence = 0; let dateTimer: ReturnType<typeof setInterval> | null = null; let activeShanghaiDate = shanghaiDate(); const search = reactive<TaskSearch>({ operationDate: props.dashboard ? activeShanghaiDate : '', category: '', systemName: '', status: '', creatorId: '', assigneeId: '', page: 0, size: 20 }); const heading = computed(() => props.dashboard ? '\u4eca\u65e5\u4efb\u52a1\u961f\u5217' : '\u4efb\u52a1\u4e2d\u5fc3'); const hasResults = computed(() => page.value.content.length > 0); const copy = { today: 'TODAY QUEUE', all: 'ALL TASKS', todayDescription: '\u6309\u64cd\u4f5c\u5f00\u59cb\u65f6\u95f4\u6392\u5217\u5f53\u5929\u5168\u90e8\u4efb\u52a1\u3002', allDescription: '\u5f00\u53d1\u4eba\u5458\u67e5\u770b\u672c\u4eba\u4efb\u52a1\uff1b\u5f53\u5929\u503c\u73ed\u548c\u7ec4\u957f\u53ef\u67e5\u770b\u6574\u4f53\u4efb\u52a1\u3002', total: '\u5171', items: '\u9879', updating: '\u6b63\u5728\u66f4\u65b0\u4efb\u52a1\u5217\u8868', loading: '\u6b63\u5728\u52a0\u8f7d\u4efb\u52a1', empty: '\u5f53\u524d\u7b5b\u9009\u6761\u4ef6\u4e0b\u6682\u65e0\u4efb\u52a1', previous: '\u4e0a\u4e00\u9875', next: '\u4e0b\u4e00\u9875', page: '\u7b2c', error: '\u4efb\u52a1\u5217\u8868\u52a0\u8f7d\u5931\u8d25' }
async function load(next: TaskSearch = search): Promise<void> { const request = ++requestSequence; loading.value = true; errorMessage.value = ''; Object.assign(search, next); try { const result = await searchTasks(cleanSearch({ ...search })); if (request === requestSequence) page.value = result } catch (error: unknown) { if (request === requestSequence) { page.value = emptyPage(); errorMessage.value = apiErrorMessage(error, copy.error) } } finally { if (request === requestSequence) loading.value = false } }
function cleanSearch(source: TaskSearch): TaskSearch { return Object.fromEntries(Object.entries(source).filter(([, value]) => value !== '' && value !== undefined && value !== null)) as TaskSearch } function applyFilters(filters: TaskSearch): void { load({ ...search, ...filters, page: 0 }) } function resetFilters(): void { load({ operationDate: props.dashboard ? shanghaiDate() : '', category: '', systemName: '', status: '', creatorId: '', assigneeId: '', page: 0, size: 20 }) } function changePage(next: number): void { if (next < 0 || next >= page.value.totalPages) return; load({ ...search, page: next }) } function openTask(id: string): void { router.push({ name: 'task-detail', params: { id } }) } const reload = () => load()
onMounted(() => { load(); if (!props.dashboard) window.addEventListener('ops-task-changed', reload); dateTimer = setInterval(() => { const current = shanghaiDate(); if (current !== activeShanghaiDate) { activeShanghaiDate = current; if (props.dashboard) resetFilters() } }, 60_000) })
watch(() => props.dashboard, resetFilters); watch(() => props.refreshToken, (next, previous) => { if (props.dashboard && next !== previous) resetFilters() }); onUnmounted(() => { requestSequence++; window.removeEventListener('ops-task-changed', reload); if (dateTimer) clearInterval(dateTimer) })
</script>
<template><section class="content-panel queue-panel ui-panel"><div class="panel-heading queue-heading"><div><p class="eyebrow">{{ dashboard ? copy.today : copy.all }}</p><h2>{{ heading }}</h2><p>{{ dashboard ? copy.todayDescription : copy.allDescription }}</p></div><span class="queue-total">{{ copy.total }} {{ page.totalElements }} {{ copy.items }}</span></div><TaskFilters :initial="search" @search="applyFilters" @reset="resetFilters" /><p v-if="errorMessage" class="form-error" role="alert">{{ errorMessage }}</p><p v-if="loading" class="queue-refresh-status" role="status">{{ hasResults ? copy.updating : copy.loading }}</p><div class="task-list" data-testid="task-list" aria-live="polite"><p v-if="!loading && !hasResults" class="task-list__empty">{{ copy.empty }}</p><TaskRow v-for="task in page.content" :key="task.id" :task="task" @open="openTask" /></div><footer v-if="page.totalPages > 1" class="pagination"><button class="ui-button" type="button" :disabled="page.page === 0" @click="changePage(page.page - 1)">{{ copy.previous }}</button><span>{{ copy.page }} {{ page.page + 1 }} / {{ page.totalPages }} {{ copy.items }}</span><button class="ui-button" type="button" :disabled="page.page + 1 >= page.totalPages" @click="changePage(page.page + 1)">{{ copy.next }}</button></footer></section></template>
<style scoped>.queue-panel { padding: var(--ui-space-5) 0 0; }.queue-heading { margin: 0 var(--ui-space-5); }.queue-total { color: var(--ui-text-secondary); font-size: .875rem; font-variant-numeric: tabular-nums; white-space: nowrap; }.queue-refresh-status { margin: 0 var(--ui-space-5) var(--ui-space-3); color: var(--ui-text-secondary); font-size: .875rem; }.task-list { min-width: 0; }.task-list__empty { display: grid; min-height: 10rem; margin: 0; place-items: center; padding: var(--ui-space-5); color: var(--ui-text-secondary); }.pagination { margin-top: var(--ui-space-2); padding: var(--ui-space-4) var(--ui-space-5); border-top: var(--ui-border-width) solid var(--ui-hairline); }@media (max-width: 680px) { .queue-heading { margin: 0 var(--ui-space-4); }.queue-total { padding-top: var(--ui-space-2); }.queue-refresh-status { margin-right: var(--ui-space-4); margin-left: var(--ui-space-4); }.pagination { justify-content: space-between; padding: var(--ui-space-4); } }</style>